import type { AnalyzedPackage, AnalyzedModule } from "../analyze.js";

/**
 * Generate import statements for all modules across all packages.
 *
 * For main package modules: import from the module.js file directly.
 * For vendor packages: import from lib/index.js (package-level) and
 * also from individual modules if they're explicitly included.
 */
export function generateImports(
  mainPkg: AnalyzedPackage | undefined,
  vendorPkgs: AnalyzedPackage[],
  stdlibPkgs: AnalyzedPackage[]
): string {
  const lines: string[] = [];
  lines.push("// Generated by @c7-digital/scribe");
  lines.push("");

  // Main package modules
  if (mainPkg) {
    for (const mod of mainPkg.modules) {
      const relPath = `./${mainPkg.name}/lib/${mod.modulePath}.js`;
      lines.push(`import * as ${mod.alias} from '${relPath}';`);
    }
  }

  // Vendor packages: import both the package-level index and specific modules
  for (const vendor of vendorPkgs) {
    // Package-level import (gives access to packageId)
    const pkgAlias = sanitizeAlias(vendor.name);
    lines.push(
      `import * as ${pkgAlias} from './${vendor.name}/lib/index.js';`
    );

    // Individual module imports
    for (const mod of vendor.modules) {
      const relPath = `./${vendor.name}/lib/${mod.modulePath}.js`;
      lines.push(`import * as ${mod.alias} from '${relPath}';`);
    }
  }

  // Stdlib packages: import package-level (needed for bundling, not exported)
  for (const stdlib of stdlibPkgs) {
    const alias = sanitizeAlias(stdlib.name);
    lines.push(
      `import * as ${alias} from './${stdlib.name}/lib/index.js';`
    );
  }

  lines.push("");
  lines.push("import * as version from './version.js';");

  return lines.join("\n");
}

/**
 * Generate named export statements for all user-facing modules.
 */
export function generateExportStatements(
  mainPkg: AnalyzedPackage | undefined,
  vendorPkgs: AnalyzedPackage[]
): string {
  const lines: string[] = [];

  // Collect all export names
  const exportNames: string[] = [];

  if (mainPkg) {
    for (const mod of mainPkg.modules) {
      exportNames.push(mod.alias);
    }
  }

  for (const vendor of vendorPkgs) {
    for (const mod of vendor.modules) {
      exportNames.push(mod.alias);
    }
  }

  if (exportNames.length > 0) {
    lines.push(`export { ${exportNames.join(", ")} };`);
  }
  lines.push("export { PACKAGE_VERSION } from './version.js';");

  return lines.join("\n");
}

/** Sanitize a package directory name to a valid JS identifier. */
function sanitizeAlias(name: string): string {
  return name.replace(/[-. ]/g, "_");
}
