/**
 * Transaction lifecycle tracking and persistence for the TransactionQueue.
 *
 * Every queued transaction is assigned a unique ID and tracked through
 * a state machine. The TransactionLog interface allows pluggable
 * persistence — apps can swap in file-based or DB-backed implementations.
 *
 * State machine:
 *   queued → preparing → prepared → submitting → completed
 *                                       ↓
 *                                     failed → retrying → submitting → ...
 *                                                              ↓
 *                                                        dead_lettered
 */
// Dynamic import to avoid breaking browser/lite builds — node:fs/promises
// is only needed by JsonlTransactionLog which is server-only.
const fsPromises = () => import("node:fs/promises");

// ── Transaction states ────────────────────────────────────────────

export type TransactionState =
  | "queued"
  | "preparing"
  | "prepared"
  | "submitting"
  | "completed"
  | "failed"
  | "retrying"
  | "dead_lettered";

export interface TransactionRecord {
  /** Unique ID for this queued transaction (generated by the queue). */
  id: string;
  /** Canton command ID used for deduplication. */
  commandId: string;
  /** Current state. */
  state: TransactionState;
  /** Estimated traffic cost in bytes (from PrepareSubmission or heuristic). */
  costEstimate?: number;
  /** Actual traffic cost in bytes (from paid_traffic_cost on completion). */
  actualCost?: number;
  /** JSON-serialized byte size of the commands (rough proxy for traffic cost). */
  jsonSizeBytes?: number;
  /** Number of retry attempts so far. */
  retryCount: number;
  /** ISO timestamp of when the transaction was enqueued. */
  enqueuedAt: string;
  /** ISO timestamp of the most recent state transition. */
  updatedAt: string;
  /** Error message if in failed/dead_lettered state. */
  error?: string;
  /** Priority level (higher = submitted first). */
  priority: number;
  /** Opaque label for grouping/filtering (e.g. "verify", "populate"). */
  tag?: string;
}

// ── TransactionLog interface ──────────────────────────────────────

export interface TransactionLog {
  /** Record a state transition. Called on every state change. */
  record(entry: TransactionRecord): Promise<void>;

  /**
   * Get all transactions currently in a given state.
   * Used for recovery on restart.
   */
  getByState(state: TransactionState): Promise<TransactionRecord[]>;

  /** Get a single transaction by ID. */
  get(id: string): Promise<TransactionRecord | undefined>;

  /** Get all tracked transactions (for diagnostics / health checks). */
  getAll(): Promise<TransactionRecord[]>;
}

// ── InMemoryTransactionLog ────────────────────────────────────────

export class InMemoryTransactionLog implements TransactionLog {
  private records = new Map<string, TransactionRecord>();

  async record(entry: TransactionRecord): Promise<void> {
    this.records.set(entry.id, { ...entry });
  }

  async getByState(state: TransactionState): Promise<TransactionRecord[]> {
    return [...this.records.values()].filter((r) => r.state === state);
  }

  async get(id: string): Promise<TransactionRecord | undefined> {
    const r = this.records.get(id);
    return r ? { ...r } : undefined;
  }

  async getAll(): Promise<TransactionRecord[]> {
    return [...this.records.values()].map((r) => ({ ...r }));
  }
}

// ── JsonlTransactionLog ──────────────────────────────────────────

/**
 * Append-only JSONL file log. Each line is a full TransactionRecord snapshot
 * at the time of the state transition. On read, the last entry per ID wins.
 *
 * This survives server crashes — on restart, read the file and find
 * transactions in "submitting" or "prepared" states to reconcile.
 */
export class JsonlTransactionLog implements TransactionLog {
  private cache = new Map<string, TransactionRecord>();
  private loaded = false;

  constructor(private readonly filePath: string) {}

  async record(entry: TransactionRecord): Promise<void> {
    this.cache.set(entry.id, { ...entry });
    const { appendFile } = await fsPromises();
    await appendFile(this.filePath, JSON.stringify(entry) + "\n", "utf-8");
  }

  private async ensureLoaded(): Promise<void> {
    if (this.loaded) return;
    this.loaded = true;
    try {
      const { readFile } = await fsPromises();
      const content = await readFile(this.filePath, "utf-8");
      for (const line of content.split("\n")) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        try {
          const record = JSON.parse(trimmed) as TransactionRecord;
          this.cache.set(record.id, record);
        } catch {
          // Skip malformed lines
        }
      }
    } catch (err: any) {
      if (err.code !== "ENOENT") throw err;
      // File doesn't exist yet — that's fine
    }
  }

  async getByState(state: TransactionState): Promise<TransactionRecord[]> {
    await this.ensureLoaded();
    return [...this.cache.values()].filter((r) => r.state === state);
  }

  async get(id: string): Promise<TransactionRecord | undefined> {
    await this.ensureLoaded();
    const r = this.cache.get(id);
    return r ? { ...r } : undefined;
  }

  async getAll(): Promise<TransactionRecord[]> {
    await this.ensureLoaded();
    return [...this.cache.values()].map((r) => ({ ...r }));
  }
}
